packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^2.0.13
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  ai: ^5.0.49
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  drizzle-orm: ^0.44.2
  next: 16.0.0
  tsdown: ^0.15.5
  zod: ^4.1.12

onlyBuiltDependencies:
  - esbuild
  - sharp
