packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/gateway': ^3.0.5
  '@ai-sdk/react': ^3.0.6
  '@axiomhq/js': ^1.0.0
  '@mastra/core': ^1.0.0-beta.19
  '@mastra/memory': ^1.0.0-beta.10
  '@mastra/pg': ^1.0.0-beta.11
  '@neondatabase/serverless': ^1.0.0
  '@tanstack/react-query': ^5.80.5
  '@trpc/client': ^11.8.1
  '@trpc/react-query': ^11.8.1
  '@trpc/server': ^11.8.1
  '@trpc/tanstack-react-query': ^11.4.2
  ai: ^6.0.6
  better-auth: ^1.2.10
  dotenv: ^17.2.2
  drizzle-kit: ^0.31.0
  drizzle-orm: 0.45.1
  nanoid: ^5.1.6
  neverthrow: 8.2.0
  next: ^16.1.1
  resend: ^4.5.1
  superjson: 2.2.6
  tsdown: ^0.15.5
  zod: ^4.3.4

onlyBuiltDependencies:
  - esbuild
  - sharp
